name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 檢出程式碼
    - name: Check out code
      uses: actions/checkout@v2

    # 設定 Node.js 版本
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 使用你的 Node.js 版本

    # 安裝依賴
    - name: Install dependencies
      run: npm install

    # 壓縮並上傳檔案至 VPS
    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      run: |
        ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no $USERNAME@$HOST "cd /var/www/your-repo && git pull origin main && npm install && pm2 restart your-app-name"
